version: '3.0'

services:
    app:
      build: .
      container_name: crud-template-service
      ports:
        - "3000:3000"
      env_file:
        - .env

    mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: "123pass"
      ports:
        - "3306:3306"
        - "33060:33060"

    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - "27017:27017"

    

